services:
  - type: web
    name: smart-youtube-agent
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python smart_youtube_agent/main_simple.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 8000
      - key: PIP_NO_CACHE_DIR
        value: "1"
